### ISSUE TITLE
ola gabriel

### ISSUE THREAD

**Issue by ruan1821** [GabrielSirtoriCorrea/Sexta-Feira-Mark_6#63]
olá gabriel,tambem tenho 16 anos e gostei muito do seu projeto inclusive eu e meu primo vamos tentar fazer,mas enfim, eu tenho uma duvida se eu quiser recriar mas nao quiser baixar o app eu poderia usar meu pc para fazer as mesmas funçoes?? ESPERO  Q ME RESPONDA :)

**Comment by GabrielSirtoriCorrea** [comment]
Fala Ruan! Fico feliz que tenha gostado! É claro que pode! Eu tbm estava pronto para fazer uma nova versão desse projeto, se você quiser posso ajudá-lo dando algumas dicas e passar links de vídeos e materiais que utilizei para criar o projeto.

**Comment by ruan1821** [comment]
> Fala Ruan! Fico feliz que tenha gostado! É claro que pode! Eu tbm estava pronto para fazer uma nova versão desse projeto, se você quiser posso ajudá-lo dando algumas dicas e passar links de vídeos e materiais que utilizei para criar o projeto.

**Comment by ruan1821** [comment]
pode sim cara,proxima semana eu vou comprar meu pc e ai vou começar a fazer,incluse tava pensando com meu primo q tem um xbox 360 mas ele nao usa,vamos pegar o kinect dele e usar como reconhecimento facial

**Comment by GabrielSirtoriCorrea** [comment]
Excelente ideia! Já vi muitos vídeos a respeito do kinect sendo utilizado para isso, se você for mais afundo existe também maneiras de fazer reconhecimento de movimento e muitas outras coisas!

**Comment by ruan1821** [comment]
sim..,ja pesquisamos sobre isso,pensei em fazer um banco de dado com as fotos das pessoas

**Comment by GabrielSirtoriCorrea** [comment]
Interessante. Mas aconselho você a armazenar as imagens em pastas mesmo, e apenas armazenar o path dela no banco de dados, foi isso que eu fiz nesse projeto, quando uma imagem precisa aparecer na interface, o programa busca pelo path dela no banco e depois mostra a imagem.

**Comment by ruan1821** [comment]
humm,vou usar essa dica :)

**Comment by GabrielSirtoriCorrea** [comment]
Se precisar de mais alguma é só chamar
